<?php

namespace App\Services\Spark;

use CodeIgniter\Log\Handlers\FileHandler;

class LogSummarizeService
{
    public function summarizeForDate(string $date, bool $dryRun = false): array
    {
        $logFile = $this->resolveDailyLogPath($date);

        if ($logFile === null) {
            return [
                'ok'         => false,
                'message'    => 'No log file found.',
                'candidates' => $this->resolveDailyLogCandidates($date),
            ];
        }

        $logDir = rtrim(dirname($logFile), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
        $outFile = $logDir . "summary-{$date}.log";
        $stateFile = $logDir . "summary-{$date}.state";

        if (! is_file($logFile)) {
            return [
                'ok'      => false,
                'message' => "No log file found for {$date}: {$logFile}",
            ];
        }

        $summaryPayload = $this->buildSummary($logFile, $date, $stateFile);

        if (! $dryRun) {
            file_put_contents($outFile, implode(PHP_EOL, $summaryPayload['lines']));

            if ($summaryPayload['max_ts'] !== null) {
                file_put_contents($stateFile, $summaryPayload['max_ts']);
            }
        }

        return [
            'ok'        => true,
            'dry_run'   => $dryRun,
            'log_file'  => $logFile,
            'out_file'  => $outFile,
            'state_file'=> $stateFile,
            'last_ts'   => $summaryPayload['last_ts'],
            'max_ts'    => $summaryPayload['max_ts'],
            'levels'    => $summaryPayload['levels'],
            'lines'     => $summaryPayload['lines'],
            'has_new'   => $summaryPayload['has_new'],
            'total'     => $summaryPayload['total'],
            'new_total' => $summaryPayload['new_total'],
        ];
    }

    private function buildSummary(string $logFile, string $date, string $stateFile): array
    {
        $levels = ['DEBUG', 'INFO', 'NOTICE', 'WARNING', 'ERROR', 'CRITICAL'];
        $entries = [];
        $newEntries = [];

        $lastProcessedTs = null;
        if (is_file($stateFile)) {
            $raw = trim((string) file_get_contents($stateFile));
            if ($raw !== '') {
                $lastProcessedTs = $raw;
            }
        }

        $lines = file($logFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $pattern = '/^(DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL)\s*-\s*' .
            '(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\s*-->\s*(.*)$/';
        $maxTsString = $lastProcessedTs;

        foreach ($lines as $line) {
            if (! preg_match($pattern, $line, $matches)) {
                continue;
            }

            $level = strtoupper(trim($matches[1]));
            $timestamp = trim($matches[2]);
            $message = trim($matches[3]);

            if (! in_array($level, $levels, true)) {
                continue;
            }

            $message = preg_replace('/\s+/', ' ', $message);
            $key = $level . '|' . $message;

            if (! isset($entries[$key])) {
                $entries[$key] = 0;
            }
            $entries[$key]++;

            $isNew = false;
            if ($lastProcessedTs !== null && $timestamp > $lastProcessedTs) {
                $isNew = true;
            }

            if ($isNew) {
                if (! isset($newEntries[$key])) {
                    $newEntries[$key] = 0;
                }
                $newEntries[$key]++;
            }

            if ($maxTsString === null || $timestamp > $maxTsString) {
                $maxTsString = $timestamp;
            }
        }

        $groupedByLevel = [];
        $newGroupedByLevel = [];

        foreach ($entries as $key => $count) {
            [$level, $message] = explode('|', $key, 2);
            $groupedByLevel[$level][$message] = $count;
        }

        foreach ($newEntries as $key => $count) {
            [$level, $message] = explode('|', $key, 2);
            $newGroupedByLevel[$level][$message] = $count;
        }

        $summary = [];
        $summary[] = '===============================================';
        $summary[] = "   MyMI Wallet — Log Summary for {$date}";
        $summary[] = '   Auto-generated by logs:summarize command';
        $summary[] = '   Grouped by (LEVEL + message)';
        $summary[] = '===============================================';
        $summary[] = '';
        $summary[] = $lastProcessedTs !== null
            ? "Last processed up to: {$lastProcessedTs}"
            : 'Last processed up to: <none> (first run for this date)';
        $summary[] = '';

        foreach ($levels as $level) {
            if (empty($groupedByLevel[$level])) {
                continue;
            }

            $summary[] = '---------------------------';
            $summary[] = "LEVEL: {$level}";
            $summary[] = '---------------------------';
            $summary[] = '';

            foreach ($groupedByLevel[$level] as $message => $count) {
                $summary[] = "[{$count} occurrence(s)]";
                $summary[] = "{$level} --> {$message}";
                $summary[] = '';
            }

            $summary[] = '';
        }

        $summary[] = '===============================================';
        $summary[] = "   HERE'S THE NEW STUFF";
        $summary[] = $lastProcessedTs !== null
            ? "   (Entries logged AFTER {$lastProcessedTs})"
            : '   (No previous timestamp recorded – nothing treated as new)';
        $summary[] = '===============================================';
        $summary[] = '';

        $hasNew = false;

        foreach ($levels as $level) {
            if (empty($newGroupedByLevel[$level])) {
                continue;
            }

            $hasNew = true;

            $summary[] = '---------------------------';
            $summary[] = "LEVEL: {$level} (NEW)";
            $summary[] = '---------------------------';
            $summary[] = '';

            foreach ($newGroupedByLevel[$level] as $message => $count) {
                $summary[] = "[{$count} NEW occurrence(s)]";
                $summary[] = "{$level} --> {$message}";
                $summary[] = '';
            }

            $summary[] = '';
        }

        if (! $hasNew && $lastProcessedTs !== null) {
            $summary[] = "No NEW log entries found after {$lastProcessedTs}.";
            $summary[] = '';
        }

        return [
            'lines'     => $summary,
            'levels'    => $levels,
            'last_ts'   => $lastProcessedTs,
            'max_ts'    => $maxTsString,
            'has_new'   => $hasNew,
            'total'     => array_sum($entries),
            'new_total' => array_sum($newEntries),
        ];
    }

    private function resolveDailyLogCandidates(string $date): array
    {
        $loggerConfig = config('Logger');
        $fileConfig = $loggerConfig->handlers[FileHandler::class] ?? [];

        $path = $fileConfig['path'] ?? WRITEPATH . 'logs/';
        $path = $path === '' ? WRITEPATH . 'logs/' : rtrim($path, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        $ext = $fileConfig['fileExtension'] ?? 'php';
        $ext = $ext === '' ? 'php' : $ext;

        $candidates = [
            $path . 'log-' . $date . '.' . $ext,
            $path . 'log-' . $date . '.php',
            $path . 'log-' . $date . '.log',
        ];

        return array_values(array_unique($candidates));
    }

    private function resolveDailyLogPath(string $date): ?string
    {
        foreach ($this->resolveDailyLogCandidates($date) as $file) {
            if (is_file($file) && filesize($file) > 0) {
                return $file;
            }
        }

        return null;
    }
}
