<?php

namespace App\Commands\AIOps;

use App\Commands\SafeBaseCommand;
use App\Commands\Support\ArtifactHelper;
use CodeIgniter\CLI\CLI;

class Init extends SafeBaseCommand
{
    protected $group = 'AIOps - Run';
    protected $name = 'aiops:init';
    protected $description = 'Initialize and validate the AIOps PR factory (one-time or rare use).';

    protected $options = [
        '--approve' => 'Required to export PR bundle to outbox.',
        '--dry-run' => 'Validate only, do not write files.',
    ];

    public function run(array $params)
    {
        [, $flags] = $this->parseParams($params);

        $approve = !empty($flags['approve']);
        $dryRun  = !empty($flags['dry-run']);

        $resolved = ArtifactHelper::resolveArtifactDirs($this->name, null);
        if (isset($resolved['error'])) {
            throw new \RuntimeException($resolved['error']);
        }

        // 1) Hard validations
        $this->assertFileExists(ROOTPATH . '.github/workflows/aiops-pr-factory.yml', 'PR factory workflow missing');
        if (! $this->assertEnvSecret('AIOPS_GH_APP_ID') || ! $this->assertEnvSecret('AIOPS_GH_APP_PRIVATE_KEY')) {
            return EXIT_ERROR;
        }

        // 2) Create a tiny bootstrap patch (docs only)
        $artifactDir = $resolved['dir'];
        $doc = $artifactDir . '/aiops-init.md';
        if (! file_exists($doc) && ! $dryRun) {
            ArtifactHelper::safeWrite($doc, "# AIOps\n\n");
        }

        $marker = "AIOps initialized at " . date('c') . "\n";
        if (! $dryRun) {
            ArtifactHelper::safeAppend($doc, $marker);
        }

        $patchPath = $artifactDir . '/aiops-init.patch';
        if (! $dryRun) {
            $output = [];
            $code = 0;
            exec('git diff', $output, $code);
            $patchContents = implode(PHP_EOL, $output) . PHP_EOL;
            ArtifactHelper::safeWrite($patchPath, $patchContents);
        }

        $summaryLines = [
            '# AIOps Init',
            '',
            '- Timestamp: ' . $resolved['timestamp'],
            '- Dry run: ' . ($dryRun ? 'yes' : 'no'),
            '- Patch path: ' . $patchPath,
        ];
        $summary = implode(PHP_EOL, $summaryLines) . PHP_EOL;
        $report = [
            'command' => $this->name,
            'timestamp' => $resolved['timestamp'],
            'dry_run' => $dryRun,
            'patch_path' => $patchPath,
            'artifact_dir' => $artifactDir,
        ];

        if (! $dryRun) {
            ArtifactHelper::writeArtifacts($artifactDir, $summary, $report);
        }

        // 3) Delegate to the real PR proposer
        CLI::write('Delegating to ops:propose-pr...');
        $args = array_values(array_filter([
            '--slug=aiops-init',
            '--title=aiops: initialize PR factory',
            '--body=Bootstrap PR generated by ops:aiops:init',
            '--patch=' . $patchPath,
            $approve ? '--approve' : null,
            $dryRun ? '--dry-run' : null,
        ], static fn ($value) => $value !== null));

        return $this->call('ops:propose-pr', $args);
    }

    private function assertFileExists(string $path, string $error)
    {
        if (!file_exists($path)) {
            throw new \RuntimeException($error);
        }
    }

    private function assertEnvSecret(string $key): bool
    {
        $value = trim((string) getenv($key));
        if ($value === '') {
            CLI::error("Missing required environment value: {$key}");
            return false;
        }

        CLI::write("Verified environment value: {$key}");
        return true;
    }
}
