<?php

namespace App\Commands\AiOps;

use App\Commands\SafeBaseCommand;
use CodeIgniter\CLI\CLI;
use App\Libraries\GitHubClient;

class PRCreate extends SafeBaseCommand
{
    protected $group = 'AiOps';
    protected $name = 'aiops:pr:create';
    protected $description = 'Create a branch, push, and open a PR (requires token + enabled flags)';

    public function run(array $params)
    {
        $settings = config('SiteSettings');

        if (!$settings->aiGithubPrEnabled) {
            CLI::error('GitHub PR creation disabled in SiteSettings.');
            return;
        }

        if (!$settings->aiAutoPrEnabled) {
            CLI::error('Auto-PR disabled (set AIOPS_AUTOPR_ENABLED=true to allow).');
            return;
        }

        $client = new GitHubClient();
        if (!$client->isConfigured()) {
            CLI::error('GitHub client not configured. Set AIOPS_GITHUB_TOKEN/OWNER/REPO env vars.');
            return;
        }

        $base = getenv('AIOPS_BASE_BRANCH') ?: 'main';
        $ts = date('Ymd_His');
        $branch = 'aiops/auto-fix-' . $ts;

        // Ensure working tree has changes
        $statusCmd = 'cd ' . escapeshellarg(ROOTPATH) . ' && git status --porcelain';
        exec($statusCmd, $statusOut);
        if (trim(implode("\n", $statusOut)) === '') {
            CLI::write('No changes to commit. Aborting PR creation.');
            return;
        }

        // Create branch
        $cmds = [
            'cd ' . escapeshellarg(ROOTPATH) . ' && git fetch origin ' . escapeshellarg($base),
            'cd ' . escapeshellarg(ROOTPATH) . ' && git checkout -b ' . escapeshellarg($branch),
            'cd ' . escapeshellarg(ROOTPATH) . 'git add -A writable/audit aiops_generated_patch.diff',
            'cd ' . escapeshellarg(ROOTPATH) . ' && git commit -m ' . escapeshellarg("AiOps auto-fix {$ts}"),
            'cd ' . escapeshellarg(ROOTPATH) . ' && git push -u origin ' . escapeshellarg($branch),
        ];

        foreach ($cmds as $c) {
            CLI::write($c);
            exec($c . ' 2>&1', $out, $code);
            foreach ($out as $line) CLI::write($line);
            if ($code !== 0) {
                CLI::error('Command failed; aborting.');
                return;
            }
        }

        $labels = array_filter(array_map('trim', explode(',', (string)getenv('AIOPS_PR_LABELS'))));
        $title = "AiOps: Auto Fix {$ts}";
        $body  = "Automated observability-driven repair.\n\n- Generated by aiops:cron:autopr\n- Includes runtime log correlation artifacts in writable/audit/\n";

        $pr = $client->createPullRequest($title, $branch, $base, $body, $labels);

        if (!$pr['ok']) {
            CLI::error('PR create failed: ' . ($pr['error'] ?? 'unknown'));
            return;
        }

        CLI::write('PR created: ' . ($pr['data']['html_url'] ?? ''));
    }
}
