<?php
namespace Config\Earnings;

class Oct142024
{
    public string $imagePath = 'assets/images/Earnings/'; 
    public string $earningsDate = '10142024'; 
    public $companies = [];

    public function __construct()
    {
        $this->companies = [
            [
                'name' => 'Bank of America',
                'symbol' => 'BAC',
                'description' => 'Focus on loan growth and the impact of rising interest rates on profits. As one of the largest financial institutions, its earnings report provided crucial insights into the broader banking sector and consumer lending trends.',
                'image' => 'Bank_of_America_logo.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/BAC_2024-10-13_08-29-32.png',
                'review' => 'Bank of America opened at $26.90 and closed at $27.15, up 0.93%. Its earnings exceeded expectations, driven by strong interest income growth amid higher rates. However, consumer loan demand showed signs of slowing.',
                'market_reaction' => 'Investors were encouraged by the resilience of interest income, but there is caution regarding loan growth in a high-rate environment.',
                'reaction_review' => '',
                'sector' => 'Banking & Finance',
                'up_down' => 'up', // up = green arrow, down = red arrow
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'BAC_2024-10-16_15-02-39-MR.png',
                'percent_gain_loss' => '0.93%',
                'open_price' => '$26.90',
                'close_price' => '$27.15',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Charles Schwab',
                'symbol' => 'SCHW',
                'description' => 'Schwab’s earnings focused on trading volatility and investment inflows. The results beat expectations, despite revenue being slightly down year-over-year.',
                'image' => 'Charles_Schwab.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/SCHW_2023-10-16.png',
                'review' => 'Schwab opened at $49.50 and closed at $52.31, up 5.67%. The stock surged on better-than-expected Q3 earnings and its integration of TD Ameritrade, alongside cost-saving initiatives targeting $1 billion in annual savings.',
                'market_reaction' => 'Strong investor support reflected confidence in Schwab’s ability to manage market volatility and strategic cost reductions.',
                'reaction_review' => '',
                'sector' => 'Financial Services',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'SCHW_2024-10-16_15-09-24.png',
                'percent_gain_loss' => '5.67%',
                'open_price' => '$49.50',
                'close_price' => '$52.31',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'BHP Group',
                'symbol' => 'BHP',
                'description' => 'BHP’s earnings offered insights into global commodity prices and demand, especially for metals like iron and copper, crucial for mining industry trends.',
                'image' => 'BHP_Group.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/BHP_2023-10-16.png',
                'review' => 'BHP opened at $60.75 and closed at $60.58, down 0.28%. The slight decline came as global commodity demand, particularly from China, remained uncertain.',
                'market_reaction' => 'Cautious investor sentiment reflected concerns over China’s economic recovery, which is critical for BHP’s growth in metals demand.',
                'reaction_review' => '',
                'sector' => 'Commodities & Mining',
                'up_down' => 'down',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'BHG_2024-10-16_15-06-07.png',
                'percent_gain_loss' => '-0.28%',
                'open_price' => '$60.75',
                'close_price' => '$60.58',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'PNC Financial Services Group',
                'symbol' => 'PNC',
                'description' => 'PNC provided insights into regional banking trends and the broader economic landscape, with a focus on loan demand and the impact of rising interest rates.',
                'image' => 'PNC_Bank.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/PNC_2023-10-16.png',
                'review' => 'PNC opened at $116.30 and closed at $118.02, up 1.48%. The bank’s steady performance in commercial banking, despite rate pressures, drove investor optimism.',
                'market_reaction' => 'PNC’s stable growth in commercial banking helped offset broader concerns about rising interest rates affecting loan demand.',
                'reaction_review' => '',
                'sector' => 'Banking & Finance',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'PNC_2024-10-16_15-06-27.png',
                'percent_gain_loss' => '1.48%',
                'open_price' => '$116.30',
                'close_price' => '$118.02',
                'earnings_date' => '2024-10-13',
            ], 
            [
                'name' => 'Netflix',
                'symbol' => 'NFLX',
                'description' => 'Expect updates on subscriber growth and the impact of pricing strategy changes. Netflix’s performance will offer insights into the competitive streaming market and consumer trends in entertainment.',
                'image' => 'Netflix.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/NFLX_2024-10-13_11-01-15.png',
                'review' => 'Netflix exceeded expectations with earnings driven by its successful ad-supported tier, which contributed to a significant increase in subscriber growth. Revenue rose by 14.4% year-over-year.',
                'market_reaction' => 'Netflix shares surged as investors were impressed with the continued subscriber growth and improving operating margins. The stock was trading near an all-time high.',
                'reaction_review' => '',
                'sector' => 'Tech & Streaming',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'NFLX_2024-10-16_15-03-54.png',
                'percent_gain_loss' => '14.4%',
                'open_price' => '$600.00',
                'close_price' => '$686.40',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Johnson & Johnson',
                'symbol' => 'JNJ',
                'description' => 'J&J’s earnings report focused on pharmaceutical developments and the resilience of its consumer health division. Key attention was on new drug pipelines and healthcare products.',
                'image' => 'Johnson_And_Johnson.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/JNJ_2024-10-13_11-11-36.png',
                'review' => 'Johnson & Johnson reported a strong performance in its pharmaceutical division, with earnings up 8%. Consumer health remained steady, but sales in the medical device segment were slightly below expectations.',
                'market_reaction' => 'The stock rose by 1.8%, as investors focused on the strength of the company’s pharmaceutical pipeline and its consistent consumer health division.',
                'reaction_review' => '',
                'sector' => 'Healthcare',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'JNJ_2024-10-16_15-10-30.png',
                'percent_gain_loss' => '1.8%',
                'open_price' => '$155.00',
                'close_price' => '$157.79',
                'earnings_date' => '2024-10-15',
            ],
            [
                'name' => 'United Airlines',
                'symbol' => 'UAL',
                'description' => 'Watch United Airlines\' report for insights into post-pandemic travel demand and how fuel prices are impacting profitability in the airline sector.',
                'image' => 'United_Airlines.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/UAL_2024-10-13_11-17-34.png',
                'review' => 'United Airlines reported strong passenger demand, but rising fuel prices weighed on profit margins.',
                'market_reaction' => 'Investors showed cautious optimism, with the stock gaining slightly despite concerns over fuel costs.',
                'reaction_review' => '',
                'sector' => 'Airlines & Transportation',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'UAL_2024-10-16_15-06-42.png',
                'percent_gain_loss' => '1.2%',
                'open_price' => '$48.20',
                'close_price' => '$48.78',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Lockheed Martin',
                'symbol' => 'LMT',
                'description' => 'Lockheed Martin’s earnings will provide insights into defense contracts and how geopolitical tensions are influencing government spending.',
                'image' => 'Lockheed_Martin.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/LMT_2024-10-13_11-19-58.png',
                'review' => 'Lockheed Martin exceeded expectations with strong demand for defense products amidst geopolitical tensions.',
                'market_reaction' => 'The stock saw a 3% jump as investors remained confident in the company’s defense contract pipeline.',
                'reaction_review' => '',
                'sector' => 'Defense & Aerospace',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'LMT_2024-10-16_15-06-59.png',
                'percent_gain_loss' => '3%',
                'open_price' => '$400.00',
                'close_price' => '$412.00',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Tesla',
                'symbol' => 'TSLA',
                'description' => 'Watch for Tesla’s vehicle delivery numbers and profit margins, especially amid growing competition in the EV market. Tesla’s report will offer a snapshot of the EV industry\'s health and future trends.',
                'image' => 'Telsa.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/TSLA_2024-10-13_11-40-25.png',
                'review' => 'Tesla reported mixed results, with strong vehicle deliveries but disappointing profit margins due to higher production costs. The company’s long-term projects, such as its “Robotaxi,” faced skepticism.',
                'market_reaction' => 'Tesla’s stock fell 6.5%, reflecting investor disappointment with margin pressures and uncertainty around long-term projects like the Robotaxi.',
                'reaction_review' => '',
                'sector' => 'Automotive & EV',
                'up_down' => 'down',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'TSLA_2024-10-16_15-04-47.png',
                'percent_gain_loss' => '-6.5%',
                'open_price' => '$800.00',
                'close_price' => '$748.00',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Morgan Stanley',
                'symbol' => 'MS',
                'description' => 'Morgan Stanley’s earnings report focused on investment banking activity and the impact of rising interest rates on their wealth management division.',
                'image' => 'Morgan_Stanley.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/MS_2024-10-13_12-30-00.png',
                'review' => 'Morgan Stanley reported strong earnings from wealth management, with overall revenue growth of 9% driven by higher interest rates. However, investment banking revenue remained weak, reflecting a broader industry slowdown.',
                'market_reaction' => 'Morgan Stanley’s stock increased by 3%, as investors were pleased with the strong performance in the wealth management division, offsetting weaker investment banking results.',
                'reaction_review' => '',
                'sector' => 'Banking & Financial Services',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'MS_2024-10-16_15-11-10.png',
                'percent_gain_loss' => '3%',
                'open_price' => '$84.00',
                'close_price' => '$86.52',
                'earnings_date' => '2024-10-15',
            ],
            [
                'name' => 'IBM',
                'symbol' => 'IBM',
                'description' => 'IBM’s report will focus on AI and cloud computing growth, key areas in the tech industry that are crucial for the company’s transformation.',
                'image' => 'IBM.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/IBM_2024-10-13_11-59-07.png',
                'review' => 'IBM reported strong growth in its AI and cloud computing segments, driving overall revenue growth despite challenges in legacy businesses.',
                'market_reaction' => 'IBM’s stock increased 2.5%, reflecting investor confidence in its ongoing digital transformation and AI focus.',
                'reaction_review' => '',
                'sector' => 'Technology & Cloud Computing',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'IBM_2024-10-16_15-07-18.png',
                'percent_gain_loss' => '2.5%',
                'open_price' => '$145.00',
                'close_price' => '$148.63',
                'earnings_date' => '2024-10-13',
            ], 
            [
                'name' => 'ASML',
                'symbol' => 'ASML',
                'description' => 'ASML’s earnings report provided critical insights into the semiconductor supply chain, with strong demand for its advanced chipmaking equipment driving growth.',
                'image' => 'ASML.jpg',
                'chart_image' => $this->imagePath . $this->earningsDate . '/ASML_2024-10-13_12-02-15.png',
                'review' => 'ASML opened at $575.00 and closed at $745.00, up 29.57%. The surge was driven by stronger-than-expected earnings, supported by high demand for its EUV lithography systems in the semiconductor industry.',
                'market_reaction' => 'ASML’s sharp rise reflected investor confidence in its dominant position in the semiconductor market, reaffirmed by strong growth projections for 2024.',
                'reaction_review' => '',
                'sector' => 'Semiconductors & Technology',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'ASML_2024-10-16_15-07-48.png',
                'percent_gain_loss' => '29.57%',
                'open_price' => '$575.00',
                'close_price' => '$745.00',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'AT&T',
                'symbol' => 'T',
                'description' => 'AT&T’s earnings focused on wireless subscriber growth and 5G infrastructure expansion. Key focus was on competition in the telecom space and how it affects revenue.',
                'image' => 'ATT.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/ATT_2024-10-16_12-04-43.png',
                'review' => 'AT&T reported steady wireless subscriber growth, but revenue slightly missed expectations due to increased competition and higher costs associated with 5G infrastructure investments.',
                'market_reaction' => 'The stock dipped by 2.2%, reflecting concerns about the costs of 5G rollout and increased competition in the wireless market.',
                'reaction_review' => '',
                'sector' => 'Telecom & Wireless',
                'up_down' => 'down',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'ATT_2024-10-16_15-12-00.png',
                'percent_gain_loss' => '-2.2%',
                'open_price' => '$16.80',
                'close_price' => '$16.43',
                'earnings_date' => '2024-10-16',
            ],
            [
                'name' => 'American Airlines',
                'symbol' => 'AAL',
                'description' => 'American Airlines reported on fuel costs and passenger demand, with focus on post-pandemic recovery and profitability amid rising fuel prices.',
                'image' => 'American_Airlines.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/AAL_2024-10-16_12-05-30.png',
                'review' => 'American Airlines posted strong passenger demand, with revenue up 12%, but rising fuel prices squeezed margins, leading to weaker-than-expected profitability.',
                'market_reaction' => 'American Airlines’ stock fell by 4.5%, as investors expressed concerns over the impact of rising fuel costs on future profitability.',
                'reaction_review' => '',
                'sector' => 'Airlines & Transportation',
                'up_down' => 'down',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'AAL_2024-10-16_15-12-40.png',
                'percent_gain_loss' => '-4.5%',
                'open_price' => '$16.00',
                'close_price' => '$15.28',
                'earnings_date' => '2024-10-16',
            ],
            [
                'name' => 'Philip Morris International',
                'symbol' => 'PM',
                'description' => 'Philip Morris will provide insights into its performance in consumer goods, especially its efforts to shift toward smoke-free products.',
                'image' => 'Philip_Morris.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/PM_2024-10-13_12-26-01.png',
                'review' => 'Philip Morris reported strong sales growth in its reduced-risk product segment, as consumers continued to shift towards smoke-free alternatives.',
                'market_reaction' => 'The stock climbed 4% as investors were optimistic about the company’s transition to smoke-free products.',
                'reaction_review' => '',
                'sector' => 'Consumer Goods',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'PM_2024-10-16_15-08-06.png',
                'percent_gain_loss' => '4%',
                'open_price' => '$95.00',
                'close_price' => '$98.80',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Snap Inc.',
                'symbol' => 'SNAP',
                'description' => 'Snap\'s earnings will give a sense of the health of the digital advertising market and user engagement trends in social media.',
                'image' => 'Snap_Inc.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/SNAP_2024-10-13_12-31-12.png',
                'review' => 'Snap reported a decline in ad revenue due to market competition and shifting user preferences, which impacted its earnings performance.',
                'market_reaction' => 'Snap shares fell 5% as investors reacted to the weaker-than-expected earnings and concerns about its long-term growth.',
                'reaction_review' => '',
                'sector' => 'Social Media & Advertising',
                'up_down' => 'down',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/' . 'SNAP_2024-10-16_15-08-24.png',
                'percent_gain_loss' => '-5%',
                'open_price' => '$10.00',
                'close_price' => '$9.50',
                'earnings_date' => '2024-10-13',
            ],
            [
                'name' => 'Procter & Gamble',
                'symbol' => 'PG',
                'description' => 'Focus will be on how inflation affects consumer demand for essential goods. As a leader in the consumer goods space, P&G’s performance sheds light on household spending habits amid rising prices.',
                'image' => 'Proctor_And_Gamble.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/PG_2024-10-18_15-01-30.png',
                'review' => 'Procter & Gamble reported net sales of $21.7 billion, a slight decline of 1%, but organic sales grew by 2%. Adjusted earnings per share beat expectations at $1.95, reflecting solid performance despite inflation pressures.',
                'market_reaction' => 'Investors responded positively, with the stock rising 1.3%, reflecting confidence in P&G’s ability to manage inflation and maintain steady growth.',
                'reaction_review' => '',
                'sector' => 'Consumer Goods',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/PG_2024-10-18_15-02-25-MR.png',
                'percent_gain_loss' => '1.3%',
                'open_price' => '$152.00',
                'close_price' => '$154.00',
                'earnings_date' => '2024-10-18',
            ],
            [
                'name' => 'HCA Healthcare',
                'symbol' => 'HCA',
                'description' => 'HCA’s earnings provide insight into healthcare trends, patient volumes, and operational costs in hospitals, especially in the post-pandemic environment.',
                'image' => 'HCA_Healthcare.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/HCA_2024-10-18_14-42-12.png',
                'review' => 'HCA reported earnings per share of $4.27, exceeding expectations, with revenues at $16.5 billion, up 5.1%. Growth was driven by increased patient volumes, especially in surgeries and outpatient services.',
                'market_reaction' => 'Stock rose 2.4% as investors reacted positively to the increased patient volumes and HCA’s ability to manage rising labor costs.',
                'reaction_review' => '',
                'sector' => 'Healthcare',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/HCA_2024-10-18_15-04-12-MR.png',
                'percent_gain_loss' => '2.4%',
                'open_price' => '$270.00',
                'close_price' => '$276.48',
                'earnings_date' => '2024-10-18',
            ],
            [
                'name' => 'Schlumberger',
                'symbol' => 'SLB',
                'description' => 'Schlumberger’s earnings are a key indicator of global energy demand and oil price fluctuations, given its role as a leading oilfield services provider.',
                'image' => 'Schlumberger.jpg',
                'chart_image' => $this->imagePath . $this->earningsDate . '/SLB_2024-10-18_12-55-42.png',
                'review' => 'Schlumberger exceeded earnings expectations with earnings per share of $0.85 and revenues of $8.6 billion, reflecting a strong year-over-year growth of 8%. Rising oil prices and increased demand for drilling services contributed to this performance.',
                'market_reaction' => 'The stock surged by 3.9%, reflecting investor optimism about continued strong performance and favorable market conditions.',
                'reaction_review' => '',
                'sector' => 'Energy',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/SLB_2024-10-18_15-06-48-MR.png',
                'percent_gain_loss' => '3.9%',
                'open_price' => '$57.50',
                'close_price' => '$59.75',
                'earnings_date' => '2024-10-18',
            ],
            // Add more companies in a similar fashion, if needed
        ];
    }
}
