<?php
namespace Config\Earnings;

class Oct212024
{
    public string $imagePath = 'assets/images/Earnings/';
    public string $earningsDate = '10212024';
    public $companies = [];

    public function __construct()
    {
        $this->companies = [
            [
                'name' => 'Bank of New York Mellon',
                'symbol' => 'BK',
                'description' => 'BNY Mellon’s earnings highlight trends in global banking and wealth management with insights on rising interest rates.',
                'image' => 'BK.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/BK_Earnings_Chart.png',
                'review' => 'BNY Mellon reported a revenue increase of 5% and EPS above expectations, benefiting from higher interest rates. However, trading revenue was lower due to market volatility.',
                'market_reaction' => 'The stock showed moderate gains following the earnings announcement as investors appreciated the stable core banking services.',
                'reaction_review' => 'Positive response attributed to BNY Mellon’s resilience in wealth management despite market fluctuations.',
                'sector' => 'Banking & Finance',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/BK_Market_Reaction.png',
                'percent_gain_loss' => '1.5%',
                'open_price' => '$40.25',
                'close_price' => '$40.85',
                'earnings_date' => '2024-10-22',
            ],
            [
                'name' => 'Prologis',
                'symbol' => 'PLD',
                'description' => 'Prologis specializes in logistics and industrial real estate with key insights into global demand for warehouse spaces.',
                'image' => 'PLD.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/PLD_Earnings_Chart.png',
                'review' => 'Prologis reported higher rental income driven by increased demand for industrial spaces. The company also raised its full-year guidance.',
                'market_reaction' => 'The stock gained as Prologis announced optimistic forward guidance and strong rental income growth.',
                'reaction_review' => 'Investors viewed Prologis’ expansion in logistics real estate favorably, especially amid e-commerce growth.',
                'sector' => 'Real Estate',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/PLD_Market_Reaction.png',
                'percent_gain_loss' => '2.8%',
                'open_price' => '$125.40',
                'close_price' => '$128.90',
                'earnings_date' => '2024-10-22',
            ],
            [
                'name' => 'Lockheed Martin',
                'symbol' => 'LMT',
                'description' => 'Lockheed Martin, key in defense, reports on aerospace contracts impacting global security and defense trends.',
                'image' => 'LMT.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/LMT_Earnings_Chart.png',
                'review' => 'Lockheed posted solid results with new contracts for defense equipment, reporting EPS above estimates at $6.75.',
                'market_reaction' => 'The stock rose after reporting strong defense sales and robust demand for defense technology.',
                'reaction_review' => 'Investors reacted positively to the increase in military contracts and defense spending.',
                'sector' => 'Aerospace & Defense',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/LMT_Market_Reaction.png',
                'percent_gain_loss' => '1.9%',
                'open_price' => '$418.00',
                'close_price' => '$426.10',
                'earnings_date' => '2024-10-22',
            ],
            [
                'name' => 'Coca-Cola',
                'symbol' => 'KO',
                'description' => 'Coca-Cola’s earnings highlight consumer demand and inflation impact, especially in managing rising input costs.',
                'image' => 'KO.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/KO_Earnings_Chart.png',
                'review' => 'Coca-Cola exceeded revenue expectations, with sales growth in Latin America and Asia. Inflationary pressures impacted margins slightly.',
                'market_reaction' => 'Investors showed confidence in Coca-Cola’s global strategy, leading to a modest stock increase.',
                'reaction_review' => 'Positive investor sentiment driven by the company’s expansion in emerging markets despite cost challenges.',
                'sector' => 'Consumer Goods',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/KO_Market_Reaction.png',
                'percent_gain_loss' => '1.2%',
                'open_price' => '$57.50',
                'close_price' => '$58.20',
                'earnings_date' => '2024-10-23',
            ],
            [
                'name' => 'General Motors',
                'symbol' => 'GM',
                'description' => 'GM’s earnings detail vehicle sales and EV transition, with implications for the automotive industry amidst competition.',
                'image' => 'GM.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/GM_Earnings_Chart.png',
                'review' => 'GM met expectations, reporting increased EV production but faced profitability challenges due to supply chain disruptions.',
                'market_reaction' => 'The stock remained stable as investors weighed EV growth against current logistical challenges.',
                'reaction_review' => 'Mixed response from investors due to the balance between EV potential and operational headwinds.',
                'sector' => 'Automotive',
                'up_down' => 'neutral',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/GM_Market_Reaction.png',
                'percent_gain_loss' => '0.5%',
                'open_price' => '$33.80',
                'close_price' => '$34.10',
                'earnings_date' => '2024-10-23',
            ],
            [
                'name' => 'Microsoft',
                'symbol' => 'MSFT',
                'description' => 'Microsoft’s earnings report focuses on cloud computing and AI innovations, with Azure and enterprise services in focus.',
                'image' => 'MSFT.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/MSFT_Earnings_Chart.png',
                'review' => 'Microsoft reported strong revenue from Azure, beating EPS expectations with notable growth in enterprise solutions.',
                'market_reaction' => 'The stock climbed, reflecting positive investor sentiment on cloud revenue growth.',
                'reaction_review' => 'Strong cloud demand and AI innovations bolstered investor confidence, driving the stock higher.',
                'sector' => 'Technology',
                'up_down' => 'up',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/MSFT_Market_Reaction.png',
                'percent_gain_loss' => '3.0%',
                'open_price' => '$340.00',
                'close_price' => '$350.20',
                'earnings_date' => '2024-10-24',
            ],
            [
                'name' => 'Texas Instruments',
                'symbol' => 'TXN',
                'description' => 'Texas Instruments’ earnings highlight industrial and automotive demand for semiconductors, signaling broader chip industry trends.',
                'image' => 'TXN.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/TXN_Earnings_Chart.png',
                'review' => 'Texas Instruments exceeded earnings expectations but noted softening consumer demand in Asia.',
                'market_reaction' => 'The stock remained stable as growth in automotive chips offset concerns over consumer segment weakness.',
                'reaction_review' => 'Positive sentiment in the automotive sector mitigated concerns from Asia’s slower consumer market.',
                'sector' => 'Semiconductors',
                'up_down' => 'neutral',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/TXN_Market_Reaction.png',
                'percent_gain_loss' => '0.8%',
                'open_price' => '$172.00',
                'close_price' => '$173.40',
                'earnings_date' => '2024-10-24',
            ],
        ];
    }
}
