#!/usr/bin/env php
<?php

/**
 * This file is part of CodeIgniter 4 framework.
 *
 * (c) CodeIgniter Foundation <admin@codeigniter.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use CodeIgniter\Boot;
use Config\Paths;

/*
 * --------------------------------------------------------------------
 * CODEIGNITER COMMAND-LINE TOOLS
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 */

/*
 *---------------------------------------------------------------
 * CHECK SERVER API
 *---------------------------------------------------------------
 */

// Refuse to run when called from php-cgi
if (str_starts_with(PHP_SAPI, 'cgi')) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

/*
 *---------------------------------------------------------------
 * CHECK PHP VERSION
 *---------------------------------------------------------------
 */

$minPhpVersion = '8.1'; // If you update this, don't forget to update `public/index.php`.
if (version_compare(PHP_VERSION, $minPhpVersion, '<')) {
    $message = sprintf(
        'Your PHP version must be %s or higher to run CodeIgniter. Current version: %s',
        $minPhpVersion,
        PHP_VERSION,
    );

    exit($message);
}

// We want errors to be shown when using it from the CLI.
error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 *---------------------------------------------------------------
 * SET THE CURRENT DIRECTORY
 *---------------------------------------------------------------
 */

// Path to the front controller
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

// Ensure the current directory is pointing to the front controller's directory
chdir(FCPATH);

$ciFlag = strtolower((string) getenv('CI')) === 'true';
$environmentRaw = strtolower((string) (getenv('ENVIRONMENT') ?: ''));
$ciEnvironmentRaw = strtolower((string) (getenv('CI_ENVIRONMENT') ?: ''));

if ($ciFlag && ($environmentRaw === 'ci' || $ciEnvironmentRaw === 'ci')) {
    fwrite(STDOUT, "[warn] CI runtime detected with ENVIRONMENT=ci; falling back to testing for Spark bootstrap.\n");
    putenv('ENVIRONMENT=testing');
    putenv('CI_ENVIRONMENT=testing');
    $_SERVER['ENVIRONMENT'] = 'testing';
    $_SERVER['CI_ENVIRONMENT'] = 'testing';
}

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 * This process sets up the path constants, loads and registers
 * our autoloader, along with Composer's, loads our constants
 * and fires up an environment-specific bootstrapping.
 */

// LOAD OUR PATHS CONFIG FILE
// This is the line that might need to be changed, depending on your folder structure.
require FCPATH . '../app/Config/Paths.php';
// ^^^ Change this line if you move your application folder

$paths = new Paths();

if (! defined('ROOTPATH')) {
    define('ROOTPATH', rtrim(realpath(FCPATH . '..') ?: (FCPATH . '..'), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR);
}

if (! defined('SUPPORTPATH')) {
    define('SUPPORTPATH', ROOTPATH . 'support' . DIRECTORY_SEPARATOR);
}

// LOAD THE FRAMEWORK BOOTSTRAP FILE
require $paths->systemDirectory . '/Boot.php';

exit(Boot::bootSpark($paths));
