<?php

namespace App\Commands\Ops;

use App\Commands\SafeBaseCommand;
use App\Commands\Support\ArtifactHelper;

class AiopsInit extends SafeBaseCommand
{
    protected $group = 'ops';
    protected $name = 'ops:aiops:init';
    protected $description = 'Initialize and validate the AIOps PR factory (one-time or rare use).';

    protected $options = [
        '--approve' => 'Required to export PR bundle to outbox.',
        '--dry-run' => 'Validate only, do not write files.',
    ];

    public function run(array $params)
    {
        [, $flags] = $this->parseParams($params);

        $approve = !empty($flags['approve']);
        $dryRun  = !empty($flags['dry-run']);


        // 1) Hard validations
        $this->assertFileExists(ROOTPATH . '.github/workflows/aiops-pr-factory.yml', 'PR factory workflow missing');
        $this->assertEnvSecret('AIOPS_GH_APP_ID');
        $this->assertEnvSecret('AIOPS_GH_APP_PRIVATE_KEY');

        // 2) Create a tiny bootstrap patch (docs only)
        $doc = ROOTPATH . 'docs/aiops/README.md';
        $docDir = dirname($doc);
        if (! is_dir($docDir)) {
            mkdir($docDir, 0775, true);
        }
        if (!file_exists($doc)) {
            if (!$dryRun) {
                ArtifactHelper::safeWrite($doc, "# AIOps\n\n");
            }
        }

        $marker = "AIOps initialized at " . date('c') . "\n";
        if (!$dryRun) {
            ArtifactHelper::safeAppend($doc, $marker);
        }

        $patchDir = ROOTPATH . 'docs/aiops/artifacts/aiops-init';
        if (! is_dir($patchDir)) {
            mkdir($patchDir, 0775, true);
        }
        $patchPath = $patchDir . '/aiops-init.patch';
        if (!$dryRun) {
            exec('git diff > ' . escapeshellarg($patchPath));
        }

        // 3) Delegate to the real PR proposer
        $this->write("Delegating to ops:propose-pr...\n");
        $args = array_values(array_filter([
            '--slug=aiops-init',
            '--title=aiops: initialize PR factory',
            '--body=Bootstrap PR generated by ops:aiops:init',
            '--patch=' . $patchPath,
            $approve ? '--approve' : null,
            $dryRun ? '--dry-run' : null,
        ], static fn ($value) => $value !== null));

        return $this->call('ops:propose-pr', $args);
    }

    private function assertFileExists(string $path, string $error)
    {
        if (!file_exists($path)) {
            throw new \RuntimeException($error);
        }
    }

    private function assertEnvSecret(string $key)
    {
        // We just verify it's configured in GitHub;
        // locally this is a placeholder check
        $this->write("Verified secret reference: {$key}\n");
    }
}
