<?php

declare(strict_types=1);

namespace App\Commands\Ops;

use App\Commands\SafeBaseCommand;
use CodeIgniter\CLI\CLI;

class FilesystemFix extends SafeBaseCommand
{
    protected $group = 'ops';
    protected $name = 'ops:filesystem:fix';
    protected $description = 'Auto-fix filesystem governance violations';

    public function run(array $params)
    {
        $this->parseParams($params);

        $repoWasClean = trim((string) shell_exec('git status --porcelain')) === '';

        command('ops:filesystem:lint --fix --report');

        $reportPath = ROOTPATH . 'docs/_ops/filesystem-lint.json';
        $payload = is_file($reportPath)
            ? json_decode((string) file_get_contents($reportPath), true)
            : [];

        $fixesApplied = (int) ($payload['fixes_applied'] ?? 0);
        $confidence = $this->averageConfidence($payload['issues'] ?? []);

        if ($fixesApplied > 0 && ! $this->isCi() && $repoWasClean && $confidence >= 0.75) {
            $this->openAutoPr($payload);
        }

        CLI::write('Filesystem auto-fix completed', 'green');

        return EXIT_SUCCESS;
    }

    private function averageConfidence(array $issues): float
    {
        if ($issues === []) {
            return 0.0;
        }

        $sum = 0.0;
        foreach ($issues as $issue) {
            $sum += (float) ($issue['confidence'] ?? 0);
        }

        return $sum / count($issues);
    }

    private function isCi(): bool
    {
        return (getenv('CI') ?: '') !== '' || (getenv('GITHUB_ACTIONS') ?: '') !== '';
    }

    private function openAutoPr(array $payload): void
    {
        $branch = 'auto/filesystem-governance-fixes';
        @shell_exec('git checkout -B ' . escapeshellarg($branch));
        @shell_exec('git add -A');
        @shell_exec('git commit -m ' . escapeshellarg('fix(ops): auto-correct filesystem governance violations'));

        $patchPath = ROOTPATH . 'docs/_ops/filesystem-governance.patch';
        @mkdir(dirname($patchPath), 0775, true);
        $diff = (string) shell_exec('git show --pretty=format: --name-only HEAD && git show --pretty=format: HEAD --');
        file_put_contents($patchPath, $diff);

        $high = (int) ($payload['confidence_summary']['high'] ?? 0);
        $medium = (int) ($payload['confidence_summary']['medium'] ?? 0);
        $manual = (int) ($payload['manual_required'] ?? 0);
        $total = (int) ($payload['fixes_applied'] ?? 0);

        $body = implode("\n", [
            '## Summary',
            'This PR was automatically generated by `ops:filesystem:fix`.',
            '',
            '## Fixes Applied',
            '- Total fixes: ' . $total,
            '- High confidence (≥0.90): ' . $high,
            '- Medium confidence (0.75–0.89): ' . $medium,
            '',
            '## Remaining Issues',
            '- Manual review required: ' . $manual,
            '',
            '## Reports',
            '- docs/_ops/filesystem-lint.md',
            '- docs/_ops/filesystem-lint-summary.md',
            '',
            'Generated by Ops Governance Engine.',
        ]);

        command(
            'ops:propose-pr '
            . '--slug=filesystem-governance-fixes '
            . '--title=' . escapeshellarg('Auto-fix: Filesystem governance violations') . ' '
            . '--body=' . escapeshellarg($body) . ' '
            . '--patch=' . escapeshellarg($patchPath) . ' '
            . '--risk=low --approve'
        );
    }
}
