from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def propose_patch(*, project_root: Path, write_path: Path, req: dict[str, Any]) -> dict[str, Any]:
    summary = str(req.get("summary") or "No summary provided").strip()
    apply_requested = bool(req.get("apply", False))
    dry_run = bool(req.get("dry_run", True))

    patches_dir = write_path / "pyops" / "patches"
    patches_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    patch_path = patches_dir / f"proposal_{timestamp}.diff"

    patch_content = (
        "# Patch proposal generated by PyOps\n"
        f"# UTC: {datetime.now(timezone.utc).isoformat()}\n"
        f"# Summary: {summary}\n"
        "# This is a placeholder patch. Replace with LLM-generated unified diff logic.\n"
    )

    patch_path.write_text(patch_content, encoding="utf-8")

    return {
        "ok": True,
        "artifacts": {
            "patch_path": str(patch_path),
        },
        "gates": {
            "git_apply_check_required": True,
            "explicit_user_confirmation_required": True,
            "tests_recommended_before_apply": True,
        },
        "mode": {
            "apply_requested": apply_requested,
            "dry_run": dry_run,
        },
        "note": "Patch creation is proposal-only; no apply is performed by this action.",
    }
