<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

class LogSummarize extends BaseCommand
{
    protected $group       = 'maintenance';
    protected $name        = 'logs:summarize';
    protected $description = 'Consolidate today\'s logs into a summary file with deduped entries (ignores timestamps).';

    public function run(array $params)
    {
        $today    = date('Y-m-d');
        $logFile  = WRITEPATH . "logs/log-{$today}.log";
        $outFile  = WRITEPATH . "logs/summary-{$today}.log";

        if (! is_file($logFile)) {
            CLI::error("No log file for today: {$logFile}");
            return;
        }

        // Levels we care about
        $levels = ['DEBUG', 'INFO', 'NOTICE', 'WARNING', 'ERROR', 'CRITICAL'];

        // Storage: [ "LEVEL|message" => count ]
        $entries = [];

        $lines = file($logFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

        // Example CI4 line:
        // CRITICAL - 2025-11-29 07:39:20 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:segment)"
        $pattern = '/^(DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL)\s*-\s*\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s*-->\s*(.*)$/';

        foreach ($lines as $line) {
            if (! preg_match($pattern, $line, $matches)) {
                continue; // skip non-log lines (PHP headers, stack trace lines, etc.)
            }

            $level   = strtoupper(trim($matches[1]));
            $message = trim($matches[2]);

            // Only track configured levels, just in case
            if (! in_array($level, $levels, true)) {
                continue;
            }

            // Optional: strip extra whitespace / normalize
            $message = preg_replace('/\s+/', ' ', $message);

            // Use LEVEL + message (no timestamp) as the key
            $key = $level . '|' . $message;

            if (! isset($entries[$key])) {
                $entries[$key] = 0;
            }

            $entries[$key]++;
        }

        // Build summary output
        $summary   = [];
        $summary[] = "===============================================";
        $summary[] = "   MyMI Wallet — Log Summary for {$today}";
        $summary[] = "   Auto-generated by logs:summarize command";
        $summary[] = "   Grouped by (LEVEL + message), timestamps ignored";
        $summary[] = "===============================================";
        $summary[] = "";

        // Group back by level for nicer display
        $groupedByLevel = [];

        foreach ($entries as $key => $count) {
            [$level, $message] = explode('|', $key, 2);
            if (! isset($groupedByLevel[$level])) {
                $groupedByLevel[$level] = [];
            }
            $groupedByLevel[$level][$message] = $count;
        }

        foreach ($levels as $level) {
            if (empty($groupedByLevel[$level])) {
                continue;
            }

            $summary[] = "---------------------------";
            $summary[] = "LEVEL: {$level}";
            $summary[] = "---------------------------";
            $summary[] = "";

            foreach ($groupedByLevel[$level] as $message => $count) {
                $summary[] = "[{$count} occurrence(s)]";
                $summary[] = "{$level} --> {$message}";
                $summary[] = "";
            }

            $summary[] = "";
        }

        file_put_contents($outFile, implode(PHP_EOL, $summary));

        CLI::write("Summary generated: {$outFile}", 'green');
    }
}
