<?php
namespace Config\Earnings;

class Oct302024
{
    public string $imagePath = 'assets/images/Earnings/';
    public string $earningsDate = '10282024';
    public $companies = [];

    public function __construct()
    {
        $this->companies = [
            [
                'name' => 'Apple Inc.',
                'symbol' => 'AAPL',
                'description' => 'Apple’s earnings report will focus on iPhone sales, Mac shipments, and developments in services and wearables. Key interest is on iPhone demand amid consumer spending slowdown.',
                'image' => 'AAPL.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/AAPL_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Technology',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/AAPL_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-10-30',
            ],
            [
                'name' => 'Alphabet Inc. (Google)',
                'symbol' => 'GOOGL',
                'description' => 'Alphabet’s report will focus on ad revenue, cloud growth, and new AI integrations. Investors are also eyeing regulatory impacts on digital advertising and AI investments.',
                'image' => 'GOOGL.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/GOOGL_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Technology & Media',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/GOOGL_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-10-30',
            ],
            [
                'name' => 'Amazon.com Inc.',
                'symbol' => 'AMZN',
                'description' => 'Amazon’s earnings will reveal insights into e-commerce growth, AWS performance, and international expansion. Key areas of focus include holiday demand projections and cost control measures.',
                'image' => 'AMZN.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/AMZN_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'E-commerce & Cloud',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/AMZN_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-10-30',
            ],
            [
                'name' => 'Intel Corporation',
                'symbol' => 'INTC',
                'description' => 'Intel’s results are expected to provide updates on its AI hardware and processor division. Key points include competition in the semiconductor space and market share in data centers.',
                'image' => 'INTC.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/INTC_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Semiconductors',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/INTC_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-10-31',
            ],
            [
                'name' => 'McDonald’s Corporation',
                'symbol' => 'MCD',
                'description' => 'McDonald’s earnings will focus on global same-store sales, menu innovations, and the impact of inflation on consumer spending habits.',
                'image' => 'MCD.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/MCD_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Restaurants & Food Service',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/MCD_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-01',
            ],
            [
                'name' => 'Visa Inc.',
                'symbol' => 'V',
                'description' => 'Visa’s earnings will provide insights on consumer spending trends and travel recovery. Key metrics include transaction volumes and cross-border transaction growth.',
                'image' => 'V.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/V_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Financial Services & Payments',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/V_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-01',
            ],
            [
                'name' => 'Meta Platforms Inc.',
                'symbol' => 'META',
                'description' => 'Meta’s report will focus on ad revenue, user engagement metrics, and the latest updates in the metaverse and AI initiatives.',
                'image' => 'META.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/META_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Social Media & Technology',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/META_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-01',
            ],
            [
                'name' => 'Exxon Mobil Corporation',
                'symbol' => 'XOM',
                'description' => 'Exxon Mobil’s report will shed light on global oil demand, production margins, and renewable investments amidst fluctuating energy prices.',
                'image' => 'XOM.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/XOM_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Energy',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/XOM_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-01',
            ],
            [
                'name' => 'Pfizer Inc.',
                'symbol' => 'PFE',
                'description' => 'Pfizer’s earnings will offer insights on vaccine sales and new drug developments, particularly in oncology and rare diseases.',
                'image' => 'PFE.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/PFE_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Pharmaceuticals',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/PFE_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-01',
            ],
            [
                'name' => 'Caterpillar Inc.',
                'symbol' => 'CAT',
                'description' => 'Caterpillar’s earnings are expected to reflect global demand for heavy machinery, mining equipment, and the state of infrastructure spending.',
                'image' => 'CAT.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/CAT_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Industrial Goods',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/CAT_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-02',
            ],
            [
                'name' => 'Starbucks Corporation',
                'symbol' => 'SBUX',
                'description' => 'Starbucks will report on same-store sales growth, digital orders, and operational costs amidst inflationary pressure on consumer goods.',
                'image' => 'SBUX.png',
                'chart_image' => $this->imagePath . $this->earningsDate . '/SBUX_Earnings_Chart.png',
                'review' => '',
                'market_reaction' => '',
                'reaction_review' => '',
                'sector' => 'Consumer Goods & Food Service',
                'up_down' => '',
                'market_reaction_chart' => $this->imagePath . $this->earningsDate . '/MR/SBUX_Market_Reaction.png',
                'percent_gain_loss' => '',
                'open_price' => '',
                'close_price' => '',
                'earnings_date' => '2024-11-02',
            ],
        ];
    }
}
