<?php

declare(strict_types=1);

namespace App\Libraries\Ops;

class PrOutboxWriter
{
    /**
     * @param array<string, mixed> $payload
     * @return array<string, string> Paths written.
     */
    public function write(array $payload): array
    {
        $date = $payload['date'] ?? date('Y-m-d');
        $dir = ROOTPATH . 'docs/_aiops/pr_outbox/' . $date;
        if (! is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        $summary = $this->renderSummary($payload);
        $changes = $this->renderChanges($payload);
        $tasks = $this->renderTasks($payload);
        $risk = $this->renderRisk($payload);

        $paths = [];
        $paths['summary'] = $dir . '/SUMMARY.md';
        $paths['changes'] = $dir . '/CHANGES.md';
        $paths['tasks'] = $dir . '/TASKS.yml';
        $paths['risk'] = $dir . '/RISK.md';

        file_put_contents($paths['summary'], $summary);
        file_put_contents($paths['changes'], $changes);
        file_put_contents($paths['tasks'], $tasks);
        file_put_contents($paths['risk'], $risk);

        if (! empty($payload['patch'])) {
            $paths['patch'] = $dir . '/PATCH.diff';
            file_put_contents($paths['patch'], (string) $payload['patch']);
        }

        return $paths;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function renderSummary(array $payload): string
    {
        $lines = [
            '# PR Summary',
            '',
            '- Date: ' . ($payload['date'] ?? date('Y-m-d')),
            '- Title: ' . ($payload['title'] ?? 'Proposal'),
            '- Source: ' . ($payload['source'] ?? 'ops'),
            '',
            '## Why',
            ($payload['why'] ?? 'Generated by ops:work --code.'),
            '',
            '## What changed',
            ($payload['summary'] ?? 'Proposal only (no code changes applied yet).'),
            '',
        ];

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function renderChanges(array $payload): string
    {
        $lines = [
            '# Changes',
            '',
        ];

        $files = $payload['files'] ?? [];
        if (! is_array($files) || $files === []) {
            $lines[] = '- No files modified in this proposal.';
        } else {
            foreach ($files as $file) {
                $lines[] = '- ' . $file;
            }
        }

        $lines[] = '';

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function renderTasks(array $payload): string
    {
        $tasks = $payload['tasks'] ?? [];
        $lines = [
            'tasks:',
        ];

        if (! is_array($tasks) || $tasks === []) {
            $lines[] = '  - id: none';
            $lines[] = '    title: No tasks processed';
            $lines[] = '    status: pending';
        } else {
            foreach ($tasks as $task) {
                $lines[] = '  - id: ' . ($task['id'] ?? $task['task_key'] ?? 'unknown');
                $lines[] = '    title: ' . ($task['title'] ?? 'Untitled task');
                $lines[] = '    status: ' . ($task['status'] ?? 'pending');
            }
        }

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function renderRisk(array $payload): string
    {
        $lines = [
            '# Risk Notes',
            '',
            '- Risk level: ' . ($payload['risk'] ?? 'low'),
            '- Rollback: revert the commit or remove generated artifacts if needed.',
            '',
            ($payload['risk_notes'] ?? '- No additional risk notes provided.'),
            '',
        ];

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }
}
