<?php

declare(strict_types=1);

namespace App\Commands\Platform;

use App\Commands\SafeBaseCommand;
use App\Libraries\Platform\CommandRunner;
use App\Libraries\Platform\ControlPlaneDispatcher;
use App\Libraries\Platform\ControlPlaneRegistry;
use CodeIgniter\CLI\CLI;

class ControlDispatch extends SafeBaseCommand
{
    protected $group = 'platform';
    protected $name = 'platform:control:dispatch';
    protected $description = 'Dispatch or dry-run actions generated by control-plane analysis.';

    protected $options = [
        '--dry-run' => 'Dry-run mode enabled by default unless --dry-run=0.',
    ];

    public function run(array $params)
    {
        [, $flags] = $this->parseParams($params);
        $dryRun = ! isset($flags['dry-run']) || (string) $flags['dry-run'] !== '0';

        $reportPath = ROOTPATH . 'docs/_platform/control_plane_report.json';
        if (! is_file($reportPath)) {
            CLI::error('Run platform:control:collect and platform:control:analyze first.');
            return;
        }

        $report = json_decode((string) file_get_contents($reportPath), true);
        if (! is_array($report)) {
            CLI::error('Control plane report is invalid JSON.');
            return;
        }

        $queue = (array) ($report['analysis_queue'] ?? []);
        $registry = new ControlPlaneRegistry();
        $dispatcher = new ControlPlaneDispatcher();
        $runner = new CommandRunner();

        $plan = $dispatcher->buildDispatchPlan($queue, $registry->loadManifests());
        $executed = [];

        foreach ($plan as $entry) {
            foreach ((array) ($entry['commands'] ?? []) as $cmd) {
                $rendered = trim(($entry['repo_path'] ? 'cd ' . escapeshellarg((string) $entry['repo_path']) . ' && ' : '') . $cmd);
                CLI::write(($dryRun ? '[dry-run] ' : '[exec] ') . $rendered, 'cyan');

                if ($dryRun) {
                    $executed[] = ['command' => $rendered, 'dry_run' => true, 'success' => true];
                    continue;
                }

                $executed[] = $runner->run($rendered, 900);
            }
        }

        $report['dispatch'] = [
            'timestamp' => gmdate(DATE_ATOM),
            'dry_run' => $dryRun,
            'plan' => $plan,
            'results' => $executed,
        ];

        file_put_contents($reportPath, json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL);
        CLI::write('Dispatch stage complete.', 'green');
    }
}
